apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u7q3njm5w-nodejs
  janus-idp.io/tekton: u7q3njm5w-nodejs
  backstage.io/kubernetes-id: u7q3njm5w-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u7q3njm5w-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
